# Generated by Django 4.2.3 on 2023-09-29 19:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("todoapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="category",
        ),
        migrations.DeleteModel(
            name="Category",
        ),
    ]
